base:
  project: winequality-project
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: E:/Data Science/INeuron/PROJECTS/Wineq_Sample_Project/data_given/winequality.csv
  #database: data_given/winequality.csv

load_data:
  raw_dataset_csv: E:/Data Science/INeuron/PROJECTS/Wineq_Sample_Project/data/raw/winequality.csv

split_data:
  train_path: E:/Data Science/INeuron/PROJECTS/Wineq_Sample_Project/data/processed/train_winequality.csv
  test_path: E:/Data Science/INeuron/PROJECTS/Wineq_Sample_Project/data/processed/test_winequality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.9
      l1_ratio: 0.4
model_dir: saved_models

#reports:
#  params: E:/Data Science/INeuron/PROJECTS/Wineq_Sample_Project/report/params.json
#  scores: E:/Data Science/INeuron/PROJECTS/Wineq_Sample_Project/report/scores.json
#
#webapp_model_dir: prediction_service/model/model.joblib